Updating for v9: update dependencies and CI
pinojs/pino-std-serializers pull request #136
Opened 2023-10-09 15:34 UTC by Ranieri93

2023-10-09 18:47 UTC, jsumners requested changes

2023-10-09 19:32 UTC, Ranieri93 commented on package.json
> +    "tap": "^18.4.5",
Ah I see, so we leave it like it is, or we move the test suite to `node:test`

2023-10-09 20:01 UTC, jsumners commented on package.json
> +    "tap": "^18.4.5",
For now, we should just leave it pinned to [16.3.9](https://www.npmjs.com/package/tap/v/16.3.9).

2023-10-10 11:40 UTC, jsumners approved these changes
Looks good to me.

2023-10-10 11:40 UTC, merged