feat: Port tests from `tap` to `node:assert` and `node:test`
pinojs/pino-std-serializers pull request #141
Opened 2024-01-22 17:52 UTC by codershiba

2024-01-23 14:27 UTC, jsumners commented on package.json
> +    "test-ci": "borp --coverage -p \"test/**/*.js\"",
Utilizing single quotes will prevent shell expansion and provide the glob directly to the runner tool:

```suggestion
    "test": "borp -p 'test/**/*.js'",
    "test-ci": "borp --coverage -p 'test/**/*.js'",
```

@mcollina does your tool support platform agnostic glob expansion?

2024-01-26 17:57 UTC, mcollina requested changes
If the test is asynchronous, you need to use an async function and add a test plan with https://github.com/mcollina/tspl.

2024-01-26 17:57 UTC, mcollina commented on test/res.test.js
> +test('can wrap response serializers', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/res.test.js
> +test('res.headers is serialized', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/res.test.js
> +test('req.url will be obtained from input request url when input request url is not an object', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/res.test.js
> +test('res.raw is available', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/res.test.js
> +test('res.raw is not enumerable', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('maps request', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('does not return excessively long object', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.raw is available', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.raw will be obtained in from input request raw property if input request raw property is truthy', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.id defaults to undefined', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.id has a non-function value', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.id will be obtained from input request info.id when input request id does not exist', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.id has a non-function value with custom id function', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.url will be obtained from input request req.path when input request url is an object', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.url will be obtained from input request url.path when input request url is an object', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.url will be obtained from input request url when input request url is not an object', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.url will be empty when input request path and url are not defined', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-01-26 17:57 UTC, mcollina commented on test/req.test.js
> +test('req.url will be obtained from input request originalUrl when available', () => {
You need the plan here. Use https://github.com/mcollina/tspl

2024-02-08 19:15 UTC, codershiba commented
Hi @mcollina , can you take a look here?

2024-02-11 15:29 UTC, mcollina approved these changes
lgtm

2024-02-11 15:30 UTC, mcollina commented
Can you drop node v14 and v16 from  CI?

2024-02-11 16:06 UTC, mcollina commented on .github/workflows/ci.yml
> +        node-version: [18]
```suggestion
        node-version: [18, 20]
```

2024-02-11 18:14 UTC, jsumners commented
Please resolve the conflicts.

2024-02-11 18:27 UTC, codershiba commented
> Please resolve the conflicts.

Resolved

2024-02-12 14:58 UTC, mcollina approved these changes
lgtm

2024-03-05 07:32 UTC, codershiba commented
@mcollina is there anything else left to do here?

2024-03-05 17:58 UTC, merged