Serialize `err.cause` in a nice way when possible
pinojs/pino-std-serializers pull request #78
Opened 2021-11-14 16:16 UTC by voxpelli

Fixes #76, see that for a description 

I did some other tweaks at #77, which I needed to get this patch working locally

2021-11-14 16:30 UTC, voxpelli commented
Opps, wrong content, will push update

2021-11-14 16:38 UTC, voxpelli commented
Fixed

2021-11-14 17:19 UTC, mcollina approved these changes
lgtm

2021-11-14 17:19 UTC, mcollina commented
Could you add some docs here?

Could you open a matching PR in the pino repo to document this too?

2021-11-14 20:01 UTC, jsumners requested changes

2021-11-14 20:01 UTC, jsumners commented on test/err.test.js
> +  t.is(serialized.message, 'foo: bar: abc')
Why is the message a concatenation of the three errors? Can you show an example of the full serialized error?

2021-11-14 21:10 UTC, voxpelli commented on test/err.test.js
> +  t.is(serialized.message, 'foo: bar: abc')
It's because all three describe the error that has happened, but at three different levels. An example:

If `err` consists of thrown and wrapped errors in these three steps:

1. `ENOENT, stat '/nonexistent'`
2. `Failed to open cache`
3. `Can't cache example.com/robots.txt`

Then when someone does:

```javascript
pino.warn(err, 'robots.txt lookup failed');
```

It will log:

```javascript
{
  "message": "Can't cache example.com/robots.txt: Failed to open cache: ENOENT, stat '/nonexistent'"
  "stack": `Error: Can't cache example.com/robots.txt
    at Object.<anonymous> (/examples/fullStack.js:5:12)
caused by: Error: Failed to open cache:
    at Object.<anonymous> (/examples/fullStack.js:3:12)
caused by: Error: ENOENT, stat '/nonexistent'
    at Object.<anonymous> (/examples/fs.js:4:15)`
}
```

2021-11-14 21:15 UTC, voxpelli commented on test/err.test.js
> +  t.is(serialized.message, 'foo: bar: abc')
So the idea is that the top most error should only describe the error on its abstraction level, not on any of the lower levels, but rather refer to the error causes for adding those description at those levels.

This makes it easy to distinguish between `Can't cache example.com/robots.txt` errors caused by `Failed to open cache` if there's also another reason going around that's maybe `Malformed cache file content`.

Here's a real life example: https://github.com/dependency-check-team/dependency-check/blob/c0537d04452098208132c6633277374dc9ad0a8d/lib/resolve-target.js#L40-L43

2021-11-15 21:34 UTC, jsumners commented on test/err.test.js
> +  t.is(serialized.message, 'foo: bar: abc')
Okay. My biggest concern was that I thought I was using the standard error serializer from this package and that this change in message shape would break me. But it seems I'm not using it. Still, this will be a semver major change unless it serializes like:

```json
{
  "message": "three",
  "stack": "...",
  "cause": {
    "message": "two",
    "stack": "...",
    "cause": {
      "message": "one",
      "stack": "..."
    }
  }
}
```

2021-11-15 21:35 UTC, jsumners commented
How much effort would it take to implement without a dependency? Going from zero to greater than zero dependencies is not ideal.

2021-11-15 21:49 UTC, voxpelli commented
> How much effort would it take to implement without a dependency? Going from zero to greater than zero dependencies is not ideal.

Not a huge effort, simplest would be a copy and paste from my module: https://github.com/voxpelli/pony-cause/blob/1f1dff84a54a44e5253fa6382c9d32d37943d747/index.js#L60-L161

100 lines including type comments then

2021-11-15 21:52 UTC, voxpelli commented on test/err.test.js
> +  t.is(serialized.message, 'foo: bar: abc')
If we keep the nested `cause` and only extend `stack`, then I think we can make it a minor, then follow up with `message` + removing redundant `cause` in a major?

Thoughts @jsumners @mcollina?

2021-11-15 22:01 UTC, mcollina commented
Let's do that

2021-11-15 22:13 UTC, jsumners commented
> > How much effort would it take to implement without a dependency? Going from zero to greater than zero dependencies is not ideal.
> 
> Not a huge effort, simplest would be a copy and paste from my module: https://github.com/voxpelli/pony-cause/blob/1f1dff84a54a44e5253fa6382c9d32d37943d747/index.js#L60-L161
> 
> 100 lines including type comments then

If that is okay with you, let's do that.

2021-11-22 13:50 UTC, voxpelli commented
Moved relevant code from `pony-cause` into this module.

What I didn't move: All of the relevant tests: https://github.com/voxpelli/pony-cause/tree/main/test They are not needed here unless individual development of the code will be done here + they are written in Mocha/Chai rather than tap, so wouldn't be a simple 1:1 copy :)

Any additional thing I should change/do` @jsumners @mcollina?

2021-11-22 14:01 UTC, voxpelli commented on test/err.test.js
> +  t.is(serialized.message, 'foo: bar: abc')
Thinking a bit more about this, I think safest would be to simply make this a major change and make all changes at once

2021-11-22 21:31 UTC, mcollina approved these changes
lgtm

2021-11-24 13:28 UTC, jsumners approved these changes
Looks good to me. Semver major.

2021-11-24 14:16 UTC, merged

2021-11-24 14:16 UTC, mcollina commented
Should we bump it in pino@7? I think so.

2021-11-24 15:14 UTC, voxpelli commented
I should add some documentation around this as well, right? Shall we create an issue and assign it to me?

2021-11-24 15:17 UTC, jsumners commented
> Should we bump it in pino@7? I think so.

I'm torn. This is a big change to the output of errors. But people shouldn't be parsing the text of logged errors anyway?

> I should add some documentation around this as well, right? Shall we create an issue and assign it to me?

Sure.