Support for aggregate errors
pinojs/pino-std-serializers pull request #87
Opened 2022-01-04 16:33 UTC by sameer-coder

Example

```js
const log = require('pino')()
const foo = new Error('foo')
const bar = new Error('bar')
const aggregate = new AggregateError([foo, bar], 'aggregated message')
log.error(aggregate)
```

Produces the following serialized output:
```json
{
  "level": 50,
  "time": 1641313649352,
  "pid": 1788,
  "hostname": "SAMEER",
  "err": {
    "type": "AggregateError",
    "message": "aggregated message",
    "stack": "AggregateError: aggregated message\n at Object.<anonymous> (pino-std-serializers\\example.js:12:19)\n at Module._compile (node:internal/modules/cjs/loader:1108:14)\n at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)\n at Module.load (node:internal/modules/cjs/loader:988:32)\n at Function.Module._load (node:internal/modules/cjs/loader:828:14)\n at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)\n at node:internal/main/run_main_module:17:47",
    "aggregateErrors": [
      {
        "type": "Error",
        "message": "foo",
        "stack": "Error: foo\n at Object.<anonymous> (pino-std-serializers\\example.js:10:15)\n at Module._compile (node:internal/modules/cjs/loader:1108:14)\n at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)\n at Module.load (node:internal/modules/cjs/loader:988:32)\n at Function.Module._load (node:internal/modules/cjs/loader:828:14)\n at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)\n at node:internal/main/run_main_module:17:47"
      },
      {
        "type": "Error",
        "message": "bar",
        "stack": "Error: bar\n at Object.<anonymous> (pino-std-serializers\\example.js:11:15)\n at Module._compile (node:internal/modules/cjs/loader:1108:14)\n at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)\n at Module.load (node:internal/modules/cjs/loader:988:32)\n at Function.Module._load (node:internal/modules/cjs/loader:828:14)\n at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)\n at node:internal/main/run_main_module:17:47"
      }
    ]
  },
  "msg": "aggregated message"
}
```

*Note: AggregateError is only supported by node 15+*

Closes #86

2022-01-04 22:49 UTC, mcollina commented on test/err.test.js
> +const { test, skip } = require('tap')
why `skip`?

2022-01-05 07:20 UTC, sameer-coder commented on test/err.test.js
> +const { test, skip } = require('tap')
I am skipping the test if node version is < 15.
Used it [here ](https://github.com/pinojs/pino-std-serializers/pull/87/files#diff-a6ff895a4ce70729791324c8118f43cffada5a9e9cfe42ea1df4a18707f2c430R9)

2022-01-05 07:50 UTC, mcollina requested changes

2022-01-05 07:50 UTC, mcollina commented on lib/err.js
> +const major = Number(process.versions.node.split('.')[0])
instead of relying on a version of Node.js, please use an existence check on `global.AggregateError`

2022-01-05 07:50 UTC, mcollina commented on test/err.test.js
> +  if (major < 15) return skip()
Please avoid the `if` and use this pattern instead:

https://github.com/pinojs/pino/blob/df49265d889788c7372e9bd9348261df712d2198/test/exit.test.js#L42

2022-01-05 07:50 UTC, mcollina commented on package.json
> +    "test-ci": "tap --cov --no-check-coverage --coverage-report=text test/**/*.test.js",
Why those changes?

2022-01-05 08:25 UTC, sameer-coder commented on package.json
> +    "test-ci": "tap --cov --no-check-coverage --coverage-report=text test/**/*.test.js",
I have only removed the quotes from the path. The `test` script wouldn't run without it

2022-01-05 08:26 UTC, sameer-coder commented on lib/err.js
> +const major = Number(process.versions.node.split('.')[0])
yep. That's a better way!

2022-01-05 10:25 UTC, mcollina approved these changes
lgtm

2022-01-05 16:03 UTC, voxpelli requested changes
Some comments, thoughts, questions – but most importantly: A note that this is susceptible to infinite recursion. Only the latter is why I set "Request changes" :)

2022-01-05 16:03 UTC, voxpelli commented on lib/err.js
> +    _err.aggregateErrors = err.errors.map(errSerializer)
This bypasses the `if (!val.hasOwnProperty(seen)) {` check and thus is susceptible to infinite recursion if an aggregate error includes itself in the list of errors.

We should add a `prevents infinite aggregate recursion` test + either add a check right here or in the beginning of `errSerializer` to ensure that infinite is aborted.

2022-01-06 11:54 UTC, sameer-coder commented on lib/err.js
> +    _err.aggregateErrors = err.errors.map(errSerializer)
@voxpelli I agree that infinite recursion is possible if the aggregate error includes itself in the list of errors but can you provide a scenario where this could happen? I think creating a new aggregate error requires you to provide an iterable of already existing errors so the list of errors cannot contain a reference to the aggregate error itself.

2022-01-06 11:55 UTC, sameer-coder commented on package.json
> +    "test-ci": "tap --cov --no-check-coverage --coverage-report=text test/**/*.test.js",
I think the it is still performed by tap. I check this on windows and it works fine

2022-01-08 15:34 UTC, mcollina commented on package.json
> +    "test-ci": "tap --cov --no-check-coverage --coverage-report=text test/**/*.test.js",
I would still prefer these to be reverted and fixed in another PR if they __must__ be changed.

2022-01-08 15:36 UTC, mcollina commented on lib/err.js
> +    _err.aggregateErrors = err.errors.map(errSerializer)
@sameer-coder I'm kind of lost on why it's impossible to write a unit test that cover this case. Can you add one anyway?

2022-01-10 14:17 UTC, jsumners commented on package.json
> +    "test-ci": "tap --cov --no-check-coverage --coverage-report=text test/**/*.test.js",
_If_ they are going to be changed, then they should be moved to `.taprc` by:

```yaml
files:
  - 'test/**/*.test.js'
```

Otherwise, the globbing will be interpreted by the shell as @voxpelli stated.

2022-01-10 14:19 UTC, jsumners requested changes

2022-01-10 14:19 UTC, jsumners commented on lib/err.js
> +const hasAggregateError = !!global.AggregateError
Can we change this check to something easier to read? Double negates are difficult.

2022-01-10 14:19 UTC, jsumners commented on lib/err.js
> +  // eslint-disable-next-line no-undef
What is this comment for? Can we resolve it another way?

2022-01-10 14:22 UTC, voxpelli commented on lib/err.js
> +const hasAggregateError = !!global.AggregateError
@jsumners Which one do you like better?

1. `global.AggregateError !== undefined`
2. `typeof global.AggregateError === 'object'`
3. `Boolean(global.AggregateError)`

(I myself like `!!`)

2022-01-10 14:23 UTC, sameer-coder commented on package.json
> +    "test-ci": "tap --cov --no-check-coverage --coverage-report=text test/**/*.test.js",
I will revert this change

2022-01-10 14:24 UTC, voxpelli commented on lib/err.js
> +  // eslint-disable-next-line no-undef
If changed to refer to `global.AggregateError`, like in the check earlier, then the comment can go away

2022-01-10 14:25 UTC, jsumners commented on lib/err.js
> +const hasAggregateError = !!global.AggregateError
`global.AggregateError !== undefined`

2022-01-10 14:28 UTC, voxpelli commented on lib/err.js
> +  // eslint-disable-next-line no-undef
Side note: we released a prerelease of an ESLint 8 based version of `eslint-config-standard` a few days ago, when that one moves through to a new major of `standard`, then this will be able to get a more proper solution. See https://github.com/eslint/eslintrc/pull/28 and https://github.com/standard/eslint-config-standard/issues/208

2022-01-12 11:18 UTC, sameer-coder commented on test/err.test.js
> +  agg1.inner = agg1
Not really sure if this test is written correctly

2022-01-12 12:54 UTC, jsumners commented on test/err.test.js
> +  agg1.inner = agg1
Wouldn't this be `agg1.errors.push(agg1)`? Although, I agree with you. I'd like to have a clear explanation of when we think this would actually happen, @voxpelli. An `AggregateError` must be initialized with an array of existing errors. Thus, it cannot be initialized with itself in the aggregate. Anyone appending to the aggregate to its `errors` list seems a Bad Idea, and a scenario we should just classify as unsupported.

http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError

Also, the spec requires at least the array of errors be present when creating a new aggregate -- https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-aggregate-error-constructor

2022-01-18 09:30 UTC, sameer-coder commented on test/err.test.js
> +  agg1.inner = agg1
@voxpelli Did you get a chance to look at this again?

2022-01-18 09:35 UTC, voxpelli commented on test/err.test.js
> +  agg1.inner = agg1
> Anyone appending to the aggregate to its errors list seems a Bad Idea, and a scenario we should just classify as unsupported.

I agree, but since the consequences are catastrophic, I think we should still prevent it.

Same would apply for Error Causes.

2022-01-18 14:24 UTC, jsumners commented on test/err.test.js
> +  agg1.inner = agg1
@mcollina do you have any thoughts on this? @davidmarkclements ?

2022-01-19 09:05 UTC, mcollina commented on test/err.test.js
> +  agg1.inner = agg1
I don't think cycles are a problem. It will be catastrophic but also very easy to debug and fix.
They will need to modify the `.errors` property manually.

To prevernt this, I would just wrap the function in a try/catch

2022-01-19 12:54 UTC, jsumners commented on test/err.test.js
> +  agg1.inner = agg1
So, to be clear, we are agreeing to remove the edge case detection in this code?

2022-01-19 13:15 UTC, voxpelli commented on test/err.test.js
> +  agg1.inner = agg1
And if someone jumps on eg. huntr.dev and reports this as a potential DDoS vector, then we'll simply say that its not valid?

I'm okay with that 👍

2022-01-19 13:22 UTC, jsumners commented on test/err.test.js
> +  agg1.inner = agg1
Yes. As stated, it's unsupported.

2022-01-19 14:19 UTC, sameer-coder commented on test/err.test.js
> +  agg1.inner = agg1
@jsumners @voxpelli  I have updated the code

2022-01-19 16:57 UTC, merged